#!/bin/sh

curl -s -o temp.xml http://thecatapi.com/api/images/get?format=xml&type=jpg&results_per_page=1 
curl -s -o temp.jpg `xmllint --xpath 'string(//response/data/images/image/url)' temp.xml`
img2txt temp.jpg
curl -s http://api.icndb.com/jokes/random | jq '.value.joke'
